#!/bin/bash

# ls 

alias ls='ls --color=auto'
alias sl='ls -r --color=auto'
alias la='ls -l --color=auto'
alias all='ls -al --color=auto'
alias l='ls'
alias s='ls -r'

# text writin
alias search='x-www-browser'

# git

# please

# alias please='sudo "$BASH" -c "$(history -p !!)"'

# archlinux 

# alias ayy="yay -S"
# alias yeet="yay -Rns"
# alias hc=herbstclient
